### PR TITLE
Enable UTF-8 support for movie names

### PR DESCRIPTION
**Pull request by BluSpoon**
When initially scanning my library the script failed on movie names that contained utf-8 chars.
This modification allowed it run through with no further issues.
I am no python dev, if there is a cleaner way please disregard this, and make it so.

### CODE REVIEW

**Comment by traubm** [comment]
I still get: 

Traceback (most recent call last):
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 526, in <module>
    collection_check(col_id)
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 258, in collection_check
    for id_check in parts:  database_check(id_check, white_name, col_json, input_id)
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 184, in database_check
    log(words[u'text'][u'in_data'].format(*mov_info(tmdb_ids.index(id_check))))
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 40, in log
    elif sys.version_info[0] == 3: f.write(pay + u"\n")
  File "C:\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2153' in position 75: character maps to <undefined>

with that patch applied.

**Comment by BluSpoon** [comment]
I am unable to reproduce the issue you are seeing (sorry!).

I am running from a FreeBSD server, with python 3.7.7
Can you try from a non Windows machine to see if it's any better?

**Comment by pto199** [comment]
Same problem as Traubm.  Changed my rcm.py file to your update but it does not resolve the problem.  I too am on Windows.  No linux machine to test with, but even if I did have one, a fix for linux only wouldn't really be the solution.

**Comment by rob-bc** [comment]
I don't have much extra info to add except I also tried with this PR and it did not fix the issue for me (OSX 10.13)

**Pull request closed without merging**
